name: Manually Update Quickstart Pages
on: workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with: 
        sparse-checkout: scripts
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
    - name: Run quickstart script
      env:
        REPO_TOKEN: ${{ secrets.DOCS_ACTION_TOKEN }}
      run: |
        cd ./scripts/update_quickstarts
        ls
        npm ci
        node update_quickstarts.js

