name: Update Quickstart Pages
on:
  push:
    branches:
      - quickstart_scripts

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with: 
        sparse-checkout: scripts
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
    - name: Run quickstart script
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        ls
        cd ./scripts/update_quickstarts
        npm ci
        ls
        node run-scripts run
