name: Manually Update Quickstart Pages
on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
    - run: ls
    - run: cd ./.github/scripts/update-quickstarts
    - run: npm ci
    - run: ls
    - name: Update readme script
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: node run-scripts run
